This add memory monitoring to livereduce
mantidproject/livereduce pull request #15
Opened 2024-11-25 05:26 UTC by rosswhitfield

Ref: [6960: [LIVEREDUCTION] Add memory monitoring](https://ornlrse.clm.ibmcloud.com/ccm/resource/itemName/com.ibm.team.workitem.WorkItem/6960)

It works by creating function running in it's own thread that is checking the memory usage. If it gets above the set percentage it will stop live data, clear the workspaces and restart live data. This seemed like a better solution then running mantid in a subprocess, MonitorLiveData is already running in it's own thread anyway.

To test I created another example in the test folder using `FakeISISEventDAE` where it's producing lots of events and the proceeding will just accumulated all the events quickly using up the available memory.

Start the fake server
```
python test/fake_event_server.py
```

start livereduce
```
python scripts/livereduce.py test/fake_event.conf
```
and you should see live data getting restarted after it uses 25% of your memory.

2024-11-25 14:18 UTC, backmari commented
Successfully ran the test. The `livereduce` process is stopped when it reaches 25% of my system memory and restarted after 1 s.
![Screenshot from 2024-11-25 09-10-10](https://github.com/user-attachments/assets/377ab233-7da6-4a9f-8b23-044052a0dc26)
The log file shows a message about exceeding the memory limit:
```
2024-11-25 09:08:47,229 - livereduce - ERROR - Memory usage 8442.67 MB exceeds limit
2024-11-25 09:08:47,229 - livereduce.LiveDataManager - INFO - Restarting Live Data and clearing workspaces
2024-11-25 09:08:47,229 - livereduce.LiveDataManager - INFO - stopping live data processing
2024-11-25 09:08:47,299 - Mantid - WARNING - Plus: Execution cancelled by user.
2024-11-25 09:08:47,339 - Mantid - WARNING - MonitorLiveData: Execution cancelled by user.
2024-11-25 09:08:48,537 - livereduce.LiveDataManager - INFO - StartLiveData({
  "AccumulationMethod": "Add",
  "FromNow": false,
  "FromStartOfRun": true,
  "Instrument": "ISIS_Event",
  "OutputWorkspace": "result",
  "PreserveEvents": true,
  "ProcessingScriptFilename": "/home/u5z/projects/livereduce/test/reduce_ISIS_Event_live_proc.py",
  "UpdateEvery": 3
})
2024-11-25 09:08:48,706 - Mantid - INFO - StartLiveData started

```

2024-11-25 15:48 UTC, peterfpeterson approved these changes
Looks good to me. I appreciate the extra information in the README for configuring this option.

2024-11-25 15:50 UTC, backmari commented on scripts/livereduce.py
> +    memory_thread = threading.Thread(target=memory_checker, args=(config, liveDataMgr))
Adding `daemon=True` allowed me to stop livereduce with Ctrl+C
```suggestion
    memory_thread = threading.Thread(target=memory_checker, args=(config, liveDataMgr), daemon=True)
```

2024-11-25 15:55 UTC, backmari requested changes
small change

2024-11-26 13:03 UTC, backmari approved these changes
Looks good to me.

2024-11-26 21:31 UTC, merged