Replace mantid_loc with CONDA_ENV
mantidproject/livereduce pull request #2
Opened 2022-10-19 10:13 UTC by jmborr

References [[Task] Imp PD [#453](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/453) Update Conf file and Startup Script](https://code.ornl.gov/sns-hfir-scse/diffraction/powder/powder-diffraction/-/issues/454)

2022-10-19 16:28 UTC, peterfpeterson commented on livereduce.spec
>  Requires: python3-inotify
I think pyinotify can get removed since the conda environment provides that

2022-10-19 16:33 UTC, peterfpeterson commented on scripts/which_python.py
> +print("PYTHON_INTERPRETER =", sys.executable)
This should be moved to a log in `livereduce.py` to be something like (first message is in there already)
```python
logger.info('logging started by user \'' + os.environ['USER'] + '\'')
logger.info(f'using python interpreter {sys.executable}')
```
and this file be removed

2022-10-19 16:37 UTC, peterfpeterson requested changes
This also needs to bump the version number in the spec file

2022-10-19 21:02 UTC, peterfpeterson reviewed
This successfully makes an rpm with the correct contents. I have not tried to connect it to an instrument yet.

2022-10-20 19:00 UTC, jmborr reviewed
looks good to me`

2022-10-20 19:00 UTC, jmborr commented on livereduce.spec
> +Requires: nsd-app-wrap
I thought this `Requires` only applied to packages retrievable with `yum`. Is this only a declaration of requirements without any validation

2022-10-20 19:10 UTC, peterfpeterson approved these changes

2022-10-20 19:17 UTC, merged